CREATE TABLE IF NOT EXISTS bookings
(
    id                int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id          integer     NOT NULL,
    username          varchar(60) NOT NULL,
    event_date_time   timestamp   NOT NULL,
    created_date_time timestamp,
    updated_date_time timestamp,
    confirmed         boolean     NOT NULL
);