graph TB
    Client[Client Applications]
    Gateway[API Gateway]
    Config[Config Server]
    Eureka[Eureka Discovery Service]
    Keycloak[Keycloak OAuth2/OpenID]
    
    subgraph Services
        EventService[Event Service]
        BookingService[Booking Service]
        NotificationService[Notification Service]
    end
    
    subgraph Databases
        EventDB[(Postgres - Event DB)]
        BookingDB[(Postgres - Booking DB)]
    end
    
    subgraph Messaging
        Kafka[Kafka Message Broker]
        
        subgraph Kafka Topics
            topic1[create-booking-request]
            topic2[create-booking-response]
            topic3[cancel-booking]
            topic4[event-changed]
            topic5[booking-updates]
            topic6[event-cancelled]
            topic7[booking-cancellations]
            topic8(booking-event-unavailable)
        end
    end

    Client --> Gateway
    Gateway --> EventService
    Gateway --> BookingService
    
    Gateway --> Keycloak
    
    EventService --> EventDB
    BookingService --> BookingDB
    
    EventService --> Eureka
    BookingService --> Eureka
    Gateway --> Eureka
    
    BookingService --> EventService
    
    BookingService --> Kafka
    NotificationService --> Kafka
    EventService --> Kafka

    style Gateway fill:#f9f,stroke:#333
    style Eureka fill:#ff9,stroke:#333
    style Config fill:#ff9,stroke:#333
    style Kafka fill:#dfd,stroke:#333
    style Keycloak fill:#fdd,stroke:#333
