graph TB
    Client[Client Applications]
    Gateway[API Gateway]
    Config[Config Server]
    Eureka[Eureka Discovery Service]
    Keycloak[Keycloak OAuth2/OpenID]
    
    subgraph Services
        EventService[Event Service]
        BookingService[Booking Service]
        NotificationService[Notification Service]
    end
    
    subgraph Databases
        EventDB[(Postgres - Event DB)]
        BookingDB[(Postgres - Booking DB)]
        NotificationDB[(Postgres - Notification DB)]
    end
    
    subgraph Messaging
        Kafka[Kafka Message Broker]
        
        subgraph Kafka Topics
            topic1[booking-created]
            topic2[booking-confirmed]
            topic3[booking-cancelled]
            topic4[event-changed]
            topic5[bookings-updated]
            topic6[event-cancelled]
            topic7[bookings-cancelled]
            topic8(booking-event-unavailable)
            topic9(event-completed)
        end
    end

    Client --> Gateway

    Gateway --> EventService
    Gateway --> BookingService
    Gateway --> NotificationService

    Gateway --> Keycloak
    EventService --> Keycloak
    NotificationService --> Keycloak
    
    EventService --> EventDB
    BookingService --> BookingDB
    NotificationService --> NotificationDB
    
    EventService --> Eureka
    BookingService --> Eureka
    NotificationService --> Eureka
    Gateway --> Eureka
    Config --> Eureka

    Gateway --> Config
    BookingService --> Config
    EventService --> Config
    NotificationService --> Config

    BookingService --> Kafka
    NotificationService --> Kafka
    EventService --> Kafka

    BookingService --> EventService

    style Gateway fill:#f9f,stroke:#333
    style Eureka fill:#ff9,stroke:#333
    style Config fill:#ff9,stroke:#333
    style Kafka fill:#dfd,stroke:#333
    style Keycloak fill:#fdd,stroke:#333
