server:
  port: 8080

spring:
  application:
    name: event-service-gateway
  config:
    import: optional:configserver:http://localhost:8888

# distinct dev-tools reload port
  devtools.livereload.port: 2720


#  Security (Oauth2/Keycloak/OIDC)
  security:
    oauth2:
      client:
        registration:
          event-service-client:
            client-name: event-service-client
            provider: keycloak
            authorization-grant-type: authorization_code
            client-id: event-service-client
            client-secret: ${KC_CLIENT_SECRET}
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/piper1970
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/piper1970/protocol/openid-connect/certs
          issuer-uri: http://localhost:9090/realms/piper1970



# logging
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.reactive.function.client: TRACE
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.cloud.gateway.routes: TRACE
    piper1970.eventgateway: DEBUG

# disable discovery with eureka
eureka:
  client:
    register-with-eureka: false

