/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package piper1970.eventservice.common.bookings.messages;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BookingsUpdated extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -863035236752974270L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BookingsUpdated\",\"namespace\":\"piper1970.eventservice.common.bookings.messages\",\"fields\":[{\"name\":\"bookingIds\",\"type\":{\"type\":\"array\",\"items\":\"int\"}},{\"name\":\"eventId\",\"type\":\"int\"},{\"name\":\"memberEmail\",\"type\":\"string\"},{\"name\":\"memberUsername\",\"type\":\"string\"},{\"name\":\"message\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BookingsUpdated> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BookingsUpdated> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BookingsUpdated> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BookingsUpdated> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BookingsUpdated> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BookingsUpdated to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BookingsUpdated from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BookingsUpdated instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BookingsUpdated fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.List<java.lang.Integer> bookingIds;
  private int eventId;
  private java.lang.CharSequence memberEmail;
  private java.lang.CharSequence memberUsername;
  private java.lang.CharSequence message;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BookingsUpdated() {}

  /**
   * All-args constructor.
   * @param bookingIds The new value for bookingIds
   * @param eventId The new value for eventId
   * @param memberEmail The new value for memberEmail
   * @param memberUsername The new value for memberUsername
   * @param message The new value for message
   */
  public BookingsUpdated(java.util.List<java.lang.Integer> bookingIds, java.lang.Integer eventId, java.lang.CharSequence memberEmail, java.lang.CharSequence memberUsername, java.lang.CharSequence message) {
    this.bookingIds = bookingIds;
    this.eventId = eventId;
    this.memberEmail = memberEmail;
    this.memberUsername = memberUsername;
    this.message = message;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bookingIds;
    case 1: return eventId;
    case 2: return memberEmail;
    case 3: return memberUsername;
    case 4: return message;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bookingIds = (java.util.List<java.lang.Integer>)value$; break;
    case 1: eventId = (java.lang.Integer)value$; break;
    case 2: memberEmail = (java.lang.CharSequence)value$; break;
    case 3: memberUsername = (java.lang.CharSequence)value$; break;
    case 4: message = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'bookingIds' field.
   * @return The value of the 'bookingIds' field.
   */
  public java.util.List<java.lang.Integer> getBookingIds() {
    return bookingIds;
  }


  /**
   * Sets the value of the 'bookingIds' field.
   * @param value the value to set.
   */
  public void setBookingIds(java.util.List<java.lang.Integer> value) {
    this.bookingIds = value;
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public int getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(int value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'memberEmail' field.
   * @return The value of the 'memberEmail' field.
   */
  public java.lang.CharSequence getMemberEmail() {
    return memberEmail;
  }


  /**
   * Sets the value of the 'memberEmail' field.
   * @param value the value to set.
   */
  public void setMemberEmail(java.lang.CharSequence value) {
    this.memberEmail = value;
  }

  /**
   * Gets the value of the 'memberUsername' field.
   * @return The value of the 'memberUsername' field.
   */
  public java.lang.CharSequence getMemberUsername() {
    return memberUsername;
  }


  /**
   * Sets the value of the 'memberUsername' field.
   * @param value the value to set.
   */
  public void setMemberUsername(java.lang.CharSequence value) {
    this.memberUsername = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.CharSequence getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.CharSequence value) {
    this.message = value;
  }

  /**
   * Creates a new BookingsUpdated RecordBuilder.
   * @return A new BookingsUpdated RecordBuilder
   */
  public static piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder newBuilder() {
    return new piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder();
  }

  /**
   * Creates a new BookingsUpdated RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BookingsUpdated RecordBuilder
   */
  public static piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder newBuilder(piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder other) {
    if (other == null) {
      return new piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder();
    } else {
      return new piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder(other);
    }
  }

  /**
   * Creates a new BookingsUpdated RecordBuilder by copying an existing BookingsUpdated instance.
   * @param other The existing instance to copy.
   * @return A new BookingsUpdated RecordBuilder
   */
  public static piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder newBuilder(piper1970.eventservice.common.bookings.messages.BookingsUpdated other) {
    if (other == null) {
      return new piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder();
    } else {
      return new piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder(other);
    }
  }

  /**
   * RecordBuilder for BookingsUpdated instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BookingsUpdated>
    implements org.apache.avro.data.RecordBuilder<BookingsUpdated> {

    private java.util.List<java.lang.Integer> bookingIds;
    private int eventId;
    private java.lang.CharSequence memberEmail;
    private java.lang.CharSequence memberUsername;
    private java.lang.CharSequence message;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.bookingIds)) {
        this.bookingIds = data().deepCopy(fields()[0].schema(), other.bookingIds);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.eventId)) {
        this.eventId = data().deepCopy(fields()[1].schema(), other.eventId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.memberEmail)) {
        this.memberEmail = data().deepCopy(fields()[2].schema(), other.memberEmail);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.memberUsername)) {
        this.memberUsername = data().deepCopy(fields()[3].schema(), other.memberUsername);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.message)) {
        this.message = data().deepCopy(fields()[4].schema(), other.message);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing BookingsUpdated instance
     * @param other The existing instance to copy.
     */
    private Builder(piper1970.eventservice.common.bookings.messages.BookingsUpdated other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.bookingIds)) {
        this.bookingIds = data().deepCopy(fields()[0].schema(), other.bookingIds);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventId)) {
        this.eventId = data().deepCopy(fields()[1].schema(), other.eventId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.memberEmail)) {
        this.memberEmail = data().deepCopy(fields()[2].schema(), other.memberEmail);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.memberUsername)) {
        this.memberUsername = data().deepCopy(fields()[3].schema(), other.memberUsername);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.message)) {
        this.message = data().deepCopy(fields()[4].schema(), other.message);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'bookingIds' field.
      * @return The value.
      */
    public java.util.List<java.lang.Integer> getBookingIds() {
      return bookingIds;
    }


    /**
      * Sets the value of the 'bookingIds' field.
      * @param value The value of 'bookingIds'.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder setBookingIds(java.util.List<java.lang.Integer> value) {
      validate(fields()[0], value);
      this.bookingIds = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'bookingIds' field has been set.
      * @return True if the 'bookingIds' field has been set, false otherwise.
      */
    public boolean hasBookingIds() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'bookingIds' field.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder clearBookingIds() {
      bookingIds = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public int getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder setEventId(int value) {
      validate(fields()[1], value);
      this.eventId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder clearEventId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'memberEmail' field.
      * @return The value.
      */
    public java.lang.CharSequence getMemberEmail() {
      return memberEmail;
    }


    /**
      * Sets the value of the 'memberEmail' field.
      * @param value The value of 'memberEmail'.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder setMemberEmail(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.memberEmail = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'memberEmail' field has been set.
      * @return True if the 'memberEmail' field has been set, false otherwise.
      */
    public boolean hasMemberEmail() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'memberEmail' field.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder clearMemberEmail() {
      memberEmail = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'memberUsername' field.
      * @return The value.
      */
    public java.lang.CharSequence getMemberUsername() {
      return memberUsername;
    }


    /**
      * Sets the value of the 'memberUsername' field.
      * @param value The value of 'memberUsername'.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder setMemberUsername(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.memberUsername = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'memberUsername' field has been set.
      * @return True if the 'memberUsername' field has been set, false otherwise.
      */
    public boolean hasMemberUsername() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'memberUsername' field.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder clearMemberUsername() {
      memberUsername = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder setMessage(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.message = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.BookingsUpdated.Builder clearMessage() {
      message = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BookingsUpdated build() {
      try {
        BookingsUpdated record = new BookingsUpdated();
        record.bookingIds = fieldSetFlags()[0] ? this.bookingIds : (java.util.List<java.lang.Integer>) defaultValue(fields()[0]);
        record.eventId = fieldSetFlags()[1] ? this.eventId : (java.lang.Integer) defaultValue(fields()[1]);
        record.memberEmail = fieldSetFlags()[2] ? this.memberEmail : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.memberUsername = fieldSetFlags()[3] ? this.memberUsername : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.message = fieldSetFlags()[4] ? this.message : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BookingsUpdated>
    WRITER$ = (org.apache.avro.io.DatumWriter<BookingsUpdated>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BookingsUpdated>
    READER$ = (org.apache.avro.io.DatumReader<BookingsUpdated>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.bookingIds.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.Integer e0: this.bookingIds) {
      actualSize0++;
      out.startItem();
      out.writeInt(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeInt(this.eventId);

    out.writeString(this.memberEmail);

    out.writeString(this.memberUsername);

    if (this.message == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.message);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<java.lang.Integer> a0 = this.bookingIds;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.Integer>((int)size0, SCHEMA$.getField("bookingIds").schema());
        this.bookingIds = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.Integer> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.Integer>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.Integer e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readInt();
          a0.add(e0);
        }
      }

      this.eventId = in.readInt();

      this.memberEmail = in.readString(this.memberEmail instanceof Utf8 ? (Utf8)this.memberEmail : null);

      this.memberUsername = in.readString(this.memberUsername instanceof Utf8 ? (Utf8)this.memberUsername : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.message = null;
      } else {
        this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.Integer> a0 = this.bookingIds;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.Integer>((int)size0, SCHEMA$.getField("bookingIds").schema());
            this.bookingIds = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.Integer> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.Integer>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.Integer e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readInt();
              a0.add(e0);
            }
          }
          break;

        case 1:
          this.eventId = in.readInt();
          break;

        case 2:
          this.memberEmail = in.readString(this.memberEmail instanceof Utf8 ? (Utf8)this.memberEmail : null);
          break;

        case 3:
          this.memberUsername = in.readString(this.memberUsername instanceof Utf8 ? (Utf8)this.memberUsername : null);
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.message = null;
          } else {
            this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










