/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package piper1970.eventservice.common.bookings.messages;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CreateBookingRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9123254824134689855L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CreateBookingRequest\",\"namespace\":\"piper1970.eventservice.common.bookings.messages\",\"fields\":[{\"name\":\"bookingId\",\"type\":\"int\"},{\"name\":\"eventId\",\"type\":\"int\"},{\"name\":\"memberUsername\",\"type\":\"string\"},{\"name\":\"memberEmail\",\"type\":\"string\"},{\"name\":\"paymentApiId\",\"type\":\"string\"},{\"name\":\"bookingCost\",\"type\":[{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":6,\"scale\":2}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<CreateBookingRequest> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CreateBookingRequest> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CreateBookingRequest> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CreateBookingRequest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CreateBookingRequest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CreateBookingRequest to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CreateBookingRequest from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CreateBookingRequest instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CreateBookingRequest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int bookingId;
  private int eventId;
  private java.lang.CharSequence memberUsername;
  private java.lang.CharSequence memberEmail;
  private java.lang.CharSequence paymentApiId;
  private java.lang.Object bookingCost;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CreateBookingRequest() {}

  /**
   * All-args constructor.
   * @param bookingId The new value for bookingId
   * @param eventId The new value for eventId
   * @param memberUsername The new value for memberUsername
   * @param memberEmail The new value for memberEmail
   * @param paymentApiId The new value for paymentApiId
   * @param bookingCost The new value for bookingCost
   */
  public CreateBookingRequest(java.lang.Integer bookingId, java.lang.Integer eventId, java.lang.CharSequence memberUsername, java.lang.CharSequence memberEmail, java.lang.CharSequence paymentApiId, java.lang.Object bookingCost) {
    this.bookingId = bookingId;
    this.eventId = eventId;
    this.memberUsername = memberUsername;
    this.memberEmail = memberEmail;
    this.paymentApiId = paymentApiId;
    this.bookingCost = bookingCost;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bookingId;
    case 1: return eventId;
    case 2: return memberUsername;
    case 3: return memberEmail;
    case 4: return paymentApiId;
    case 5: return bookingCost;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bookingId = (java.lang.Integer)value$; break;
    case 1: eventId = (java.lang.Integer)value$; break;
    case 2: memberUsername = (java.lang.CharSequence)value$; break;
    case 3: memberEmail = (java.lang.CharSequence)value$; break;
    case 4: paymentApiId = (java.lang.CharSequence)value$; break;
    case 5: bookingCost = value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'bookingId' field.
   * @return The value of the 'bookingId' field.
   */
  public int getBookingId() {
    return bookingId;
  }


  /**
   * Sets the value of the 'bookingId' field.
   * @param value the value to set.
   */
  public void setBookingId(int value) {
    this.bookingId = value;
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public int getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(int value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'memberUsername' field.
   * @return The value of the 'memberUsername' field.
   */
  public java.lang.CharSequence getMemberUsername() {
    return memberUsername;
  }


  /**
   * Sets the value of the 'memberUsername' field.
   * @param value the value to set.
   */
  public void setMemberUsername(java.lang.CharSequence value) {
    this.memberUsername = value;
  }

  /**
   * Gets the value of the 'memberEmail' field.
   * @return The value of the 'memberEmail' field.
   */
  public java.lang.CharSequence getMemberEmail() {
    return memberEmail;
  }


  /**
   * Sets the value of the 'memberEmail' field.
   * @param value the value to set.
   */
  public void setMemberEmail(java.lang.CharSequence value) {
    this.memberEmail = value;
  }

  /**
   * Gets the value of the 'paymentApiId' field.
   * @return The value of the 'paymentApiId' field.
   */
  public java.lang.CharSequence getPaymentApiId() {
    return paymentApiId;
  }


  /**
   * Sets the value of the 'paymentApiId' field.
   * @param value the value to set.
   */
  public void setPaymentApiId(java.lang.CharSequence value) {
    this.paymentApiId = value;
  }

  /**
   * Gets the value of the 'bookingCost' field.
   * @return The value of the 'bookingCost' field.
   */
  public java.lang.Object getBookingCost() {
    return bookingCost;
  }


  /**
   * Sets the value of the 'bookingCost' field.
   * @param value the value to set.
   */
  public void setBookingCost(java.lang.Object value) {
    this.bookingCost = value;
  }

  /**
   * Creates a new CreateBookingRequest RecordBuilder.
   * @return A new CreateBookingRequest RecordBuilder
   */
  public static piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder newBuilder() {
    return new piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder();
  }

  /**
   * Creates a new CreateBookingRequest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CreateBookingRequest RecordBuilder
   */
  public static piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder newBuilder(piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder other) {
    if (other == null) {
      return new piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder();
    } else {
      return new piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder(other);
    }
  }

  /**
   * Creates a new CreateBookingRequest RecordBuilder by copying an existing CreateBookingRequest instance.
   * @param other The existing instance to copy.
   * @return A new CreateBookingRequest RecordBuilder
   */
  public static piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder newBuilder(piper1970.eventservice.common.bookings.messages.CreateBookingRequest other) {
    if (other == null) {
      return new piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder();
    } else {
      return new piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder(other);
    }
  }

  /**
   * RecordBuilder for CreateBookingRequest instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CreateBookingRequest>
    implements org.apache.avro.data.RecordBuilder<CreateBookingRequest> {

    private int bookingId;
    private int eventId;
    private java.lang.CharSequence memberUsername;
    private java.lang.CharSequence memberEmail;
    private java.lang.CharSequence paymentApiId;
    private java.lang.Object bookingCost;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.bookingId)) {
        this.bookingId = data().deepCopy(fields()[0].schema(), other.bookingId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.eventId)) {
        this.eventId = data().deepCopy(fields()[1].schema(), other.eventId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.memberUsername)) {
        this.memberUsername = data().deepCopy(fields()[2].schema(), other.memberUsername);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.memberEmail)) {
        this.memberEmail = data().deepCopy(fields()[3].schema(), other.memberEmail);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.paymentApiId)) {
        this.paymentApiId = data().deepCopy(fields()[4].schema(), other.paymentApiId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.bookingCost)) {
        this.bookingCost = data().deepCopy(fields()[5].schema(), other.bookingCost);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing CreateBookingRequest instance
     * @param other The existing instance to copy.
     */
    private Builder(piper1970.eventservice.common.bookings.messages.CreateBookingRequest other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.bookingId)) {
        this.bookingId = data().deepCopy(fields()[0].schema(), other.bookingId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventId)) {
        this.eventId = data().deepCopy(fields()[1].schema(), other.eventId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.memberUsername)) {
        this.memberUsername = data().deepCopy(fields()[2].schema(), other.memberUsername);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.memberEmail)) {
        this.memberEmail = data().deepCopy(fields()[3].schema(), other.memberEmail);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.paymentApiId)) {
        this.paymentApiId = data().deepCopy(fields()[4].schema(), other.paymentApiId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.bookingCost)) {
        this.bookingCost = data().deepCopy(fields()[5].schema(), other.bookingCost);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'bookingId' field.
      * @return The value.
      */
    public int getBookingId() {
      return bookingId;
    }


    /**
      * Sets the value of the 'bookingId' field.
      * @param value The value of 'bookingId'.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder setBookingId(int value) {
      validate(fields()[0], value);
      this.bookingId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'bookingId' field has been set.
      * @return True if the 'bookingId' field has been set, false otherwise.
      */
    public boolean hasBookingId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'bookingId' field.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder clearBookingId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public int getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder setEventId(int value) {
      validate(fields()[1], value);
      this.eventId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder clearEventId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'memberUsername' field.
      * @return The value.
      */
    public java.lang.CharSequence getMemberUsername() {
      return memberUsername;
    }


    /**
      * Sets the value of the 'memberUsername' field.
      * @param value The value of 'memberUsername'.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder setMemberUsername(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.memberUsername = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'memberUsername' field has been set.
      * @return True if the 'memberUsername' field has been set, false otherwise.
      */
    public boolean hasMemberUsername() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'memberUsername' field.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder clearMemberUsername() {
      memberUsername = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'memberEmail' field.
      * @return The value.
      */
    public java.lang.CharSequence getMemberEmail() {
      return memberEmail;
    }


    /**
      * Sets the value of the 'memberEmail' field.
      * @param value The value of 'memberEmail'.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder setMemberEmail(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.memberEmail = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'memberEmail' field has been set.
      * @return True if the 'memberEmail' field has been set, false otherwise.
      */
    public boolean hasMemberEmail() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'memberEmail' field.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder clearMemberEmail() {
      memberEmail = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentApiId' field.
      * @return The value.
      */
    public java.lang.CharSequence getPaymentApiId() {
      return paymentApiId;
    }


    /**
      * Sets the value of the 'paymentApiId' field.
      * @param value The value of 'paymentApiId'.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder setPaymentApiId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.paymentApiId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentApiId' field has been set.
      * @return True if the 'paymentApiId' field has been set, false otherwise.
      */
    public boolean hasPaymentApiId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'paymentApiId' field.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder clearPaymentApiId() {
      paymentApiId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'bookingCost' field.
      * @return The value.
      */
    public java.lang.Object getBookingCost() {
      return bookingCost;
    }


    /**
      * Sets the value of the 'bookingCost' field.
      * @param value The value of 'bookingCost'.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder setBookingCost(java.lang.Object value) {
      validate(fields()[5], value);
      this.bookingCost = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'bookingCost' field has been set.
      * @return True if the 'bookingCost' field has been set, false otherwise.
      */
    public boolean hasBookingCost() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'bookingCost' field.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingRequest.Builder clearBookingCost() {
      bookingCost = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CreateBookingRequest build() {
      try {
        CreateBookingRequest record = new CreateBookingRequest();
        record.bookingId = fieldSetFlags()[0] ? this.bookingId : (java.lang.Integer) defaultValue(fields()[0]);
        record.eventId = fieldSetFlags()[1] ? this.eventId : (java.lang.Integer) defaultValue(fields()[1]);
        record.memberUsername = fieldSetFlags()[2] ? this.memberUsername : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.memberEmail = fieldSetFlags()[3] ? this.memberEmail : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.paymentApiId = fieldSetFlags()[4] ? this.paymentApiId : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.bookingCost = fieldSetFlags()[5] ? this.bookingCost :  defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CreateBookingRequest>
    WRITER$ = (org.apache.avro.io.DatumWriter<CreateBookingRequest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CreateBookingRequest>
    READER$ = (org.apache.avro.io.DatumReader<CreateBookingRequest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










