/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package piper1970.eventservice.common.bookings.messages;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CreateBookingResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7962963523279279365L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CreateBookingResponse\",\"namespace\":\"piper1970.eventservice.common.bookings.messages\",\"fields\":[{\"name\":\"bookingId\",\"type\":\"int\"},{\"name\":\"eventId\",\"type\":\"int\"},{\"name\":\"memberUsername\",\"type\":\"string\"},{\"name\":\"memberEmail\",\"type\":\"string\"},{\"name\":\"paymentApiId\",\"type\":\"string\"},{\"name\":\"paymentToken\",\"type\":[\"null\",{\"type\":\"string\",\"logicalType\":\"uuid\"}]},{\"name\":\"bookingStatus\",\"type\":{\"type\":\"enum\",\"name\":\"BookingStatus\",\"symbols\":[\"CONFIRMED\",\"CANCELLED\"]}},{\"name\":\"message\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
  }

  private static final BinaryMessageEncoder<CreateBookingResponse> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CreateBookingResponse> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CreateBookingResponse> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CreateBookingResponse> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CreateBookingResponse> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CreateBookingResponse to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CreateBookingResponse from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CreateBookingResponse instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CreateBookingResponse fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int bookingId;
  private int eventId;
  private java.lang.CharSequence memberUsername;
  private java.lang.CharSequence memberEmail;
  private java.lang.CharSequence paymentApiId;
  private java.util.UUID paymentToken;
  private piper1970.eventservice.common.bookings.messages.BookingStatus bookingStatus;
  private java.lang.CharSequence message;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CreateBookingResponse() {}

  /**
   * All-args constructor.
   * @param bookingId The new value for bookingId
   * @param eventId The new value for eventId
   * @param memberUsername The new value for memberUsername
   * @param memberEmail The new value for memberEmail
   * @param paymentApiId The new value for paymentApiId
   * @param paymentToken The new value for paymentToken
   * @param bookingStatus The new value for bookingStatus
   * @param message The new value for message
   */
  public CreateBookingResponse(java.lang.Integer bookingId, java.lang.Integer eventId, java.lang.CharSequence memberUsername, java.lang.CharSequence memberEmail, java.lang.CharSequence paymentApiId, java.util.UUID paymentToken, piper1970.eventservice.common.bookings.messages.BookingStatus bookingStatus, java.lang.CharSequence message) {
    this.bookingId = bookingId;
    this.eventId = eventId;
    this.memberUsername = memberUsername;
    this.memberEmail = memberEmail;
    this.paymentApiId = paymentApiId;
    this.paymentToken = paymentToken;
    this.bookingStatus = bookingStatus;
    this.message = message;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bookingId;
    case 1: return eventId;
    case 2: return memberUsername;
    case 3: return memberEmail;
    case 4: return paymentApiId;
    case 5: return paymentToken;
    case 6: return bookingStatus;
    case 7: return message;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bookingId = (java.lang.Integer)value$; break;
    case 1: eventId = (java.lang.Integer)value$; break;
    case 2: memberUsername = (java.lang.CharSequence)value$; break;
    case 3: memberEmail = (java.lang.CharSequence)value$; break;
    case 4: paymentApiId = (java.lang.CharSequence)value$; break;
    case 5: paymentToken = (java.util.UUID)value$; break;
    case 6: bookingStatus = (piper1970.eventservice.common.bookings.messages.BookingStatus)value$; break;
    case 7: message = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'bookingId' field.
   * @return The value of the 'bookingId' field.
   */
  public int getBookingId() {
    return bookingId;
  }


  /**
   * Sets the value of the 'bookingId' field.
   * @param value the value to set.
   */
  public void setBookingId(int value) {
    this.bookingId = value;
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public int getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(int value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'memberUsername' field.
   * @return The value of the 'memberUsername' field.
   */
  public java.lang.CharSequence getMemberUsername() {
    return memberUsername;
  }


  /**
   * Sets the value of the 'memberUsername' field.
   * @param value the value to set.
   */
  public void setMemberUsername(java.lang.CharSequence value) {
    this.memberUsername = value;
  }

  /**
   * Gets the value of the 'memberEmail' field.
   * @return The value of the 'memberEmail' field.
   */
  public java.lang.CharSequence getMemberEmail() {
    return memberEmail;
  }


  /**
   * Sets the value of the 'memberEmail' field.
   * @param value the value to set.
   */
  public void setMemberEmail(java.lang.CharSequence value) {
    this.memberEmail = value;
  }

  /**
   * Gets the value of the 'paymentApiId' field.
   * @return The value of the 'paymentApiId' field.
   */
  public java.lang.CharSequence getPaymentApiId() {
    return paymentApiId;
  }


  /**
   * Sets the value of the 'paymentApiId' field.
   * @param value the value to set.
   */
  public void setPaymentApiId(java.lang.CharSequence value) {
    this.paymentApiId = value;
  }

  /**
   * Gets the value of the 'paymentToken' field.
   * @return The value of the 'paymentToken' field.
   */
  public java.util.UUID getPaymentToken() {
    return paymentToken;
  }


  /**
   * Sets the value of the 'paymentToken' field.
   * @param value the value to set.
   */
  public void setPaymentToken(java.util.UUID value) {
    this.paymentToken = value;
  }

  /**
   * Gets the value of the 'bookingStatus' field.
   * @return The value of the 'bookingStatus' field.
   */
  public piper1970.eventservice.common.bookings.messages.BookingStatus getBookingStatus() {
    return bookingStatus;
  }


  /**
   * Sets the value of the 'bookingStatus' field.
   * @param value the value to set.
   */
  public void setBookingStatus(piper1970.eventservice.common.bookings.messages.BookingStatus value) {
    this.bookingStatus = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.CharSequence getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.CharSequence value) {
    this.message = value;
  }

  /**
   * Creates a new CreateBookingResponse RecordBuilder.
   * @return A new CreateBookingResponse RecordBuilder
   */
  public static piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder newBuilder() {
    return new piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder();
  }

  /**
   * Creates a new CreateBookingResponse RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CreateBookingResponse RecordBuilder
   */
  public static piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder newBuilder(piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder other) {
    if (other == null) {
      return new piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder();
    } else {
      return new piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder(other);
    }
  }

  /**
   * Creates a new CreateBookingResponse RecordBuilder by copying an existing CreateBookingResponse instance.
   * @param other The existing instance to copy.
   * @return A new CreateBookingResponse RecordBuilder
   */
  public static piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder newBuilder(piper1970.eventservice.common.bookings.messages.CreateBookingResponse other) {
    if (other == null) {
      return new piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder();
    } else {
      return new piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder(other);
    }
  }

  /**
   * RecordBuilder for CreateBookingResponse instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CreateBookingResponse>
    implements org.apache.avro.data.RecordBuilder<CreateBookingResponse> {

    private int bookingId;
    private int eventId;
    private java.lang.CharSequence memberUsername;
    private java.lang.CharSequence memberEmail;
    private java.lang.CharSequence paymentApiId;
    private java.util.UUID paymentToken;
    private piper1970.eventservice.common.bookings.messages.BookingStatus bookingStatus;
    private java.lang.CharSequence message;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.bookingId)) {
        this.bookingId = data().deepCopy(fields()[0].schema(), other.bookingId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.eventId)) {
        this.eventId = data().deepCopy(fields()[1].schema(), other.eventId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.memberUsername)) {
        this.memberUsername = data().deepCopy(fields()[2].schema(), other.memberUsername);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.memberEmail)) {
        this.memberEmail = data().deepCopy(fields()[3].schema(), other.memberEmail);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.paymentApiId)) {
        this.paymentApiId = data().deepCopy(fields()[4].schema(), other.paymentApiId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.paymentToken)) {
        this.paymentToken = data().deepCopy(fields()[5].schema(), other.paymentToken);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.bookingStatus)) {
        this.bookingStatus = data().deepCopy(fields()[6].schema(), other.bookingStatus);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.message)) {
        this.message = data().deepCopy(fields()[7].schema(), other.message);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing CreateBookingResponse instance
     * @param other The existing instance to copy.
     */
    private Builder(piper1970.eventservice.common.bookings.messages.CreateBookingResponse other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.bookingId)) {
        this.bookingId = data().deepCopy(fields()[0].schema(), other.bookingId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventId)) {
        this.eventId = data().deepCopy(fields()[1].schema(), other.eventId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.memberUsername)) {
        this.memberUsername = data().deepCopy(fields()[2].schema(), other.memberUsername);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.memberEmail)) {
        this.memberEmail = data().deepCopy(fields()[3].schema(), other.memberEmail);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.paymentApiId)) {
        this.paymentApiId = data().deepCopy(fields()[4].schema(), other.paymentApiId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.paymentToken)) {
        this.paymentToken = data().deepCopy(fields()[5].schema(), other.paymentToken);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.bookingStatus)) {
        this.bookingStatus = data().deepCopy(fields()[6].schema(), other.bookingStatus);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.message)) {
        this.message = data().deepCopy(fields()[7].schema(), other.message);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'bookingId' field.
      * @return The value.
      */
    public int getBookingId() {
      return bookingId;
    }


    /**
      * Sets the value of the 'bookingId' field.
      * @param value The value of 'bookingId'.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder setBookingId(int value) {
      validate(fields()[0], value);
      this.bookingId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'bookingId' field has been set.
      * @return True if the 'bookingId' field has been set, false otherwise.
      */
    public boolean hasBookingId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'bookingId' field.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder clearBookingId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public int getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder setEventId(int value) {
      validate(fields()[1], value);
      this.eventId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder clearEventId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'memberUsername' field.
      * @return The value.
      */
    public java.lang.CharSequence getMemberUsername() {
      return memberUsername;
    }


    /**
      * Sets the value of the 'memberUsername' field.
      * @param value The value of 'memberUsername'.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder setMemberUsername(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.memberUsername = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'memberUsername' field has been set.
      * @return True if the 'memberUsername' field has been set, false otherwise.
      */
    public boolean hasMemberUsername() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'memberUsername' field.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder clearMemberUsername() {
      memberUsername = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'memberEmail' field.
      * @return The value.
      */
    public java.lang.CharSequence getMemberEmail() {
      return memberEmail;
    }


    /**
      * Sets the value of the 'memberEmail' field.
      * @param value The value of 'memberEmail'.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder setMemberEmail(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.memberEmail = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'memberEmail' field has been set.
      * @return True if the 'memberEmail' field has been set, false otherwise.
      */
    public boolean hasMemberEmail() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'memberEmail' field.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder clearMemberEmail() {
      memberEmail = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentApiId' field.
      * @return The value.
      */
    public java.lang.CharSequence getPaymentApiId() {
      return paymentApiId;
    }


    /**
      * Sets the value of the 'paymentApiId' field.
      * @param value The value of 'paymentApiId'.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder setPaymentApiId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.paymentApiId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentApiId' field has been set.
      * @return True if the 'paymentApiId' field has been set, false otherwise.
      */
    public boolean hasPaymentApiId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'paymentApiId' field.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder clearPaymentApiId() {
      paymentApiId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentToken' field.
      * @return The value.
      */
    public java.util.UUID getPaymentToken() {
      return paymentToken;
    }


    /**
      * Sets the value of the 'paymentToken' field.
      * @param value The value of 'paymentToken'.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder setPaymentToken(java.util.UUID value) {
      validate(fields()[5], value);
      this.paymentToken = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentToken' field has been set.
      * @return True if the 'paymentToken' field has been set, false otherwise.
      */
    public boolean hasPaymentToken() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'paymentToken' field.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder clearPaymentToken() {
      paymentToken = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'bookingStatus' field.
      * @return The value.
      */
    public piper1970.eventservice.common.bookings.messages.BookingStatus getBookingStatus() {
      return bookingStatus;
    }


    /**
      * Sets the value of the 'bookingStatus' field.
      * @param value The value of 'bookingStatus'.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder setBookingStatus(piper1970.eventservice.common.bookings.messages.BookingStatus value) {
      validate(fields()[6], value);
      this.bookingStatus = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'bookingStatus' field has been set.
      * @return True if the 'bookingStatus' field has been set, false otherwise.
      */
    public boolean hasBookingStatus() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'bookingStatus' field.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder clearBookingStatus() {
      bookingStatus = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder setMessage(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.message = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public piper1970.eventservice.common.bookings.messages.CreateBookingResponse.Builder clearMessage() {
      message = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CreateBookingResponse build() {
      try {
        CreateBookingResponse record = new CreateBookingResponse();
        record.bookingId = fieldSetFlags()[0] ? this.bookingId : (java.lang.Integer) defaultValue(fields()[0]);
        record.eventId = fieldSetFlags()[1] ? this.eventId : (java.lang.Integer) defaultValue(fields()[1]);
        record.memberUsername = fieldSetFlags()[2] ? this.memberUsername : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.memberEmail = fieldSetFlags()[3] ? this.memberEmail : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.paymentApiId = fieldSetFlags()[4] ? this.paymentApiId : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.paymentToken = fieldSetFlags()[5] ? this.paymentToken : (java.util.UUID) defaultValue(fields()[5]);
        record.bookingStatus = fieldSetFlags()[6] ? this.bookingStatus : (piper1970.eventservice.common.bookings.messages.BookingStatus) defaultValue(fields()[6]);
        record.message = fieldSetFlags()[7] ? this.message : (java.lang.CharSequence) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CreateBookingResponse>
    WRITER$ = (org.apache.avro.io.DatumWriter<CreateBookingResponse>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CreateBookingResponse>
    READER$ = (org.apache.avro.io.DatumReader<CreateBookingResponse>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










