CREATE TABLE IF NOT EXISTS booking_confirmations
(
    id                     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id             int         NOT NULL,
    event_id               int         NOT NULL,
    confirmation_string    UUID        NOT NULL,
    confirmation_date_time timestamp   NOT NULL,
    duration_in_minutes    int         NOT NULL,
    confirmation_status    varchar(30) NOT NULL
);