server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: events-gateway

# distinct dev-tools reload port
  devtools.livereload.port: 2720


  # Database (r2dbc - reactive)
  r2dbc.url: r2dbc:h2:mem:///authentication

#  Security
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}

  # Routing
  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/bookings/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - TokenRelay=
        - id: event-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/events/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - TokenRelay=
        - id: member-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/members/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - TokenRelay=

# Actuator health checks
management:
  endpoint.health.probes.enabled: true
  health:
    readinessstate.enabled: true
    livenessstate.enabled: true


# logging
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: TRACE
    org.springframework.cloud.gateway: TRACE
    piper1970.eventgateway: DEBUG

