CREATE TABLE IF NOT EXISTS events
(
    id                 int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facilitator        varchar(60)   NOT NULL,
    title              text          NOT NULL,
    description        text,
    location           text          NOT NULL,
    event_date_time    timestamp     NOT NULL,
    created_date_time  timestamp,
    updated_date_time  timestamp,
    cost               numeric(6, 2) NOT NULL,
    available_bookings smallint      NOT NULL,
    event_status       varchar(30)   NOT NULL
);